# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'Payments Demo' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Payments Demo
  pod 'Alamofire', '~> 3.5'
  pod 'MBProgressHUD', '~> 1.0'

end
